---

- name: Creates nginx static file directory
  file: path=/var/www/data state=directory

- name: Copy nginx conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Restart nginx
  service: name=nginx state=restarted

- name: Install git
  apt: name=git state=latest update_cache=yes
  become: true

- name: Install maven
  apt: name=maven state=latest update_cache=yes
  become: true

- name: clone scigraph github repo
  git: repo=https://github.com/SciGraph/SciGraph
       dest=/opt/SciGraph
  become: true

- name: clone dipper repo
  git: repo=https://github.com/monarch-initiative/dipper.git
       dest=/opt/dipper
  become: true

- name: clone monarch cypher queries github repo
  git: repo=https://github.com/monarch-initiative/monarch-cypher-queries.git
       dest=/opt/monarch-cypher-queries
  become: true

- name: build SciGraph
  command: bash -c 'cd /opt/SciGraph && mvn clean install -DskipTests'
  become: true

- name: package dipper curie file
  command: bash -c 'cd /opt/dipper/maven && mvn clean install'
  become: true

- name: package cypher dynamic queries file
  command: bash -c 'cd /opt/monarch-cypher-queries && mvn clean install'
  become: true

# - name: download graph
#   get_url: url=http://kato.crbs.ucsd.edu/scigraph.tgz dest=/var/www/data

# loca testing
- name: copy graph
  copy: src=/home/jnguyenxuan/scigraph.tgz dest=/var/www/data

- name: Creates directory
  file: path=/var/scigraph state=directory

- name: expand graph
  unarchive: src=/var/www/data/scigraph.tgz dest=/var/scigraph copy=no

- name: clone scigraph docker
  git: repo=https://github.com/monarch-initiative/SciGraph-docker-monarch-data.git
       dest=/opt/SciGraph-docker-monarch-data
  become: true

- name: build docker images
  command: bash -c 'cd /opt/SciGraph-docker-monarch-data && mvn clean package'
  become: true

- name: start service
  command: docker run -v /var/scigraph:/scigraph -d -p 9000:9000 --name scigraph-services scigraph-services-monarch
  become: true
