# Test playbook for Vagrant box:
# vagrant destroy && vagrant up
# vagrant ssh
# vagrant provision // rerun the playbook
- hosts: all
  become: true
  roles:
    - java7-oracle
    - nginx
    - apollo
  vars:
    target_user: vagrant
