# Test playbook for Vagrant box:
# vagrant destroy && vagrant up
# vagrant ssh
# vagrant provision // rerun the playbook
- hosts: all
  sudo: true
  roles:
    - java8-oracle
    - nginx
    - docker
    - scigraph-base
    - scigraph-ontology
