# Test playbook for Vagrant box:
# vagrant destroy && vagrant up
# vagrant ssh
- hosts: all
  sudo_user: vagrant
  roles:
    - nvm
    - nodejs
    - supervisor
    - nginx
    - monarch-app
  vars:
    target_user: vagrant
