---
- name: Creates nginx static file directory
  file: path=/var/www/data state=directory
  become: true

- name: Copy nginx conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  become: true

- name: Restart nginx
  service: name=nginx state=restarted
  become: true

# Then scp data from /export/www/html/monarch
