####
#### This file defines a temporary development setup with Ansible.
####
#### See README.md.
####
---
## Fiddly location URL variables.
GOLR_LOOKUP_URL:
  comment: The public location of the GOlr server ask information from about seeding, etc.
  type: url
  value: http://solr.monarchinitiative.org/solr/monarchAutocomplete/
GOLR_NEO_LOOKUP_URL:
  comment: The public location of the NEO GOlr server to ask information from for autocomplete, etc.
  type: url
  value: http://solr.monarchinitiative.org/solr/monarchAutocomplete/
GOLR_LOCATION:
  comment: The actual unprotected location of the GOlr server to load to (if different from GOLR_LOOKUP_URL).
  type: url
  value: http://solr.monarchinitiative.org/solr/monarchAutocomplete/
BARISTA_LOOKUP_URL:
  comment: Define where Noctua looks for Barista.
  type: url
  value: http://monarch-barista-prod.monarchinitiative.org
BARISTA_LOCATION:
  comment: Location that Barista should think it is. (may be different than that in BARISTA_LOOKUP_URL)
  type: number
  value: http://localhost:3400
NOCTUA_CONTEXT:
  comment: NOCTUA_CONTEXT=(go|monarch|<string>)
  type: string
  value: monarch
NOCTUA_LOOKUP_URL:
  comment: The external self-reference URL that Noctua should use.
  type: url
  value: http://create.monarchinitiative.org
NOCTUA_LOCATION:
  comment: Location that Noctua should think it is internally.
  type: url
  value: http://localhost:8910
MINERVA_LOCATION:
  comment: The location of the minerva to communicate with.
  type: url
  value: http://localhost:6800
## File locations.
USER_DATA:
  comment: The location of the known users for the system (GO metadata users.yaml style).
  type: directory
  value: /opt/monarch-phenote/webphenote-config/users.yaml
NOCTUA_MODELS:
  comment: The directory of the noctua models to use and monitor.
  type: directory
  value: /opt/monarch-models/models/
ONTOLOGY_CATALOG:
  comment: The catalog to use for Minerva.
  type: file
  value: /opt/monarch-phenote/webphenote-config/cached-models/catalog.xml
#  value: /opt/geneontology.org/trunk/ontology/extensions/catalog-v001.xml
ONTOLOGY_LIST:
  comment: The ontologies to use for Minerva.
  type: list
  value:
    - http://purl.obolibrary.org/obo/upheno/monarch.owl
WORKBENCHES:
  comment: The location of workbench directories to add to the configuration.
  type: list
  value:
    - './workbenches'
## JVM preferences.
MINERVA MAX_MEMORY:
  comment: The maximum memory that can be taken by Minerva.
  type: number
  value: 4
## Graph preferences.
COLLAPSIBLE_RELATIONS:
  comment: The relations that the graph system will attempt to collapse.
  type: list
  value:
    - RO:0002333
    - BFO:0000066
    - RO:0002233
    - RO:0002488
COLLAPSIBLE_REVERSE_RELATIONS:
  comment: The relations that the graph system will attempt to collapse, with the edges flowing the other direction.
  type: list
  value:
    - BFO:0000051
## Other service definitions.
DEFAULT_APP_DEFINITION:
  comment: The application profile to use at startup.
  type: string
  value: minerva_local
## Barista variables.
BARISTA_REPL_PORT:
  comment: The port to start the Barista REPL on. If not defined, will not start listener.
  type: number
  value: 9090
APP_DEFINITIONS:
  comment: A list of resources that Barista will allow public access to.
  type: list
  value:
    - id: minerva_local
      target: http://localhost:6800
      public:
        - m3Batch
        - seed/fromProcess
    - id: minerva_public
      target: http://toaster.lbl.gov:6800
      public:
        - m3Batch
        - seed/fromProcess
    - id: minerva_public_dev
      target: http://toaster.lbl.gov:6799
      public:
        - m3Batch
        - seed/fromProcess
    - id: minerva_monarch_dev
      target: http://poole.monarchinitiative.org:6800
      public:
        - m3Batch
        - seed/fromProcess

