---

- name: install docker apt-key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: enable docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: install the required packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - linux-image-extra-{{ ansible_kernel }}
   - docker-engine
